#source 'https://gitcafe.com/akuandev/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'
#为提升pod 安装速度，把github的spec改成国内的镜像，如果镜像失效可以改回github  source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.ms.netease.com/commonlibraryios/podspec.git'
#source 'https://git.ms.netease.com/faclient/faspecs.git'
#source 'https://git.ms.netease.com/netease-precious-metals-client/ldcpspecs.git'
#source 'https://git.ms.netease.com/neteaselottery/ldcpspecs.git'
#source 'https://git.ms.netease.com/preciousmetals/ldpmspecs.git'

platform :ios, '6.0'
inhibit_all_warnings!

target 'IPhoneDemo' do

pod 'AFNetworking','~>1.3.0'

pod 'JLRoutes'
pod 'LDJSBridge'
#pod 'NetEasePatch'
pod 'SDWebImage', '~> 3.7.3'


pod 'Aspects'

pod 'JSONKit-NoWarning'

pod 'MobileAnalysis'

pod 'Reachability','~>3.2'

pod 'ZipArchive','~>1.3.0'

#pod 'J2ObjC' ,:path=>'/Users/wangxiang/workspace/tools/J2ObjC'

pod 'LDCommonLibrary', :git =>'https://git.ms.netease.com/commonlibraryios/ntcommonlibrary.git'

pod 'NimbusKit-AttributedLabel', '~> 1.0.0'

pod 'CommonCrypto','~>1.1'

#pod 'GoogleMaps','~>1.10.2'

pod 'MPCoachMarks','~>0.0.7'

pod 'NSData+Base64','~>1.0.0'

pod 'SBJson','~>4.0.2'

pod 'UIToast','~>0.0.2'

#pod 'ZXingObjC', '~> 3.1.0'

pod 'Masonry', '~> 0.6.2'

pod 'MMPlaceHolder'

end
